default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: socialist_dev

test:
  <<: *default
  database: socialist_test

production:
  <<: *default
  database: socialist_production
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  username: socialist
  password: <%= ENV['SOCIALIST_DATABASE_PASSWORD'] %>

staging:
  database: socialist_staging
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
